### PR TITLE
Project Key Validation fixed

### LINKED ISSUE #22: Project key must be 3 - 6 lowercase alphanumeric characters
**Describe the bug**
`terraform validate` says that project keys must be 3-6 characters only. This seems to be fine for Artifactory 7.21.12 (on-premise) but on Artifactory Cloud (7.34.4) one can use 3-10 characters.

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`: `"version" : "7.34.4",  "revision" : "73404900"`
- [ ] Your version of terraform: 1.1.0

**Expected behavior**
While creating projects against Artifactory Cloud 7.34.4 we get the info that only 3-6 characters are allowed whereas on 7.34.4 3-10 are allowed.

**Additional context**

### PR DESCRIPTION
**Pull request by dasmanas**
closes #22 
Project key validation is fixed as per latest Artifactory release version.

### CODE REVIEW

**Review by maheshjfrog — DISMISSED** [review]

**Review by chb0github — APPROVED** [review]

File: pkg/projects/resource_project_test.go [hunk 1]
```diff
@@ -144,14 +144,14 @@ func TestAccProjectUpdateKey(t *testing.T) {
...
-				Check:  resource.ComposeTestCheckFunc(
+				Check: resource.ComposeTestCheckFunc(
 					resource.TestCheckResourceAttr(resourceName, "key", key1),
 					resource.TestCheckResourceAttr(resourceName, "display_name", name),
 				),
 			},
 			{
 				Config: configWithNewKey,
-				Check:  resource.ComposeTestCheckFunc(
+				Check: resource.ComposeTestCheckFunc(
```
Comment (danielmkn) [inline pkg/projects/resource_project_test.go:154]: please run `make fmt`, it will fix such issues with formatting

File: pkg/projects/validators.go [hunk 2]
```diff
@@ -2,6 +2,8 @@ package projects
 
 import (
 	"fmt"
+	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
+	"regexp"
 
 	"github.com/gorhill/cronexpr"
```
Comment (danielmkn) [inline pkg/projects/validators.go:8]: same here. `make fmt` will also sort the imports

File: pkg/projects/validators.go [hunk 3]
```diff
@@ -2,6 +2,8 @@ package projects
 
 import (
 	"fmt"
+	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
```
Comment (danielmkn) [inline pkg/projects/validators.go:5]: same here. make fmt will also sort the imports

**Review by danielmkn — CHANGES_REQUESTED** [review]
Please run `make fmt`

**Review by danielmkn — APPROVED** [review]

**Review by chb0github — APPROVED** [review]

File: pkg/projects/resource_project.go [hunk 4]
```diff
@@ -51,13 +51,11 @@ func projectResource() *schema.Resource {
...
-			ForceNew: true,
-			ValidateDiagFunc: validation.ToDiagFunc(
-				validation.StringMatch(regexp.MustCompile("^[a-z0-9]{3,6}$"), "key must be 3 - 6 lowercase alphanumeric characters"),
-			),
-			Description: "The Project Key is added as a prefix to resources created within a Project. This field is mandatory and supports only 3 - 6 lowercase alphanumeric characters. Must begin with a letter. For example: us1a.",
+			Type:             schema.TypeString,
+			Required:         true,
+			ForceNew:         true,
+			ValidateDiagFunc: projectKeyValidator,
+			Description:      "The Project Key is added as a prefix to resources created within a Project. This field is mandatory and supports only 3 - 6 lowercase alphanumeric characters. Must begin with a letter. For example: us1a.",
```
Comment (martinm82) [inline pkg/projects/resource_project.go:58]: This should be updated to 3 - 10, right?
