### PR TITLE
Ignore unassigning (non-existent) repository error when destroying project resource

### LINKED ISSUE #56: Provider attempts to remove already deleted repo from project
**Describe the bug**
Provider does not refresh current state before running destroy and attempts to remove already deleted repo.

Selected output:
```
# module.project["projectA"].project.this will be destroyed
  # (because module.project["projectA"] is not in configuration)
  - resource "project" "this" {
      - block_deployments_on_limit = false -> null
      - display_name               = "projectA" -> null
      - email_notification         = true -> null
      - id                         = "projectA" -> null
      - key                        = "projectA" -> null
      - max_storage_in_gibibytes   = -1 -> null
      - repos                      = [
          - "projectA-docker",
        ] -> null

      - admin_privileges {
          - index_resources  = true -> null
          - manage_members   = true -> null
          - manage_resources = true -> null
        }

      - group {
          - name  = "projectA-contributors" -> null
          - roles = [
              - "Contributor",
            ] -> null
        }
    }

...

│ Error: failed to delete repos for project: failed to delete repo projectA-docker:
│ 404 DELETE https://blahblah.jfrog.io/access/api/v1/projects/_/attach/repositories/projectA-docker
│ {
│   "errors" : [ {
│     "code" : "NOT_FOUND",
│     "message" : "Could not find resource `projectA-docker`; type `repo` in Projects configuration"
│   } ]
│ }
```

State file:
```json
 {
      "module": "module.project[\"projectA\"]",
      "mode": "managed",
      "type": "project",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/jfrog/project\"]",
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "admin_privileges": [
              {
                "index_resources": true,
                "manage_members": true,
                "manage_resources": true
              }
            ],
            "block_deployments_on_limit": false,
            "description": "",
            "display_name": "projectA",
            "email_notification": true,
            "group": [
              {
                "name": "projectA-contributors",
                "roles": [
                  "Contributor"
                ]
              }
            ],
            "id": "projectA",
            "key": "projectA",
            "max_storage_in_gibibytes": -1,
            "member": [],
            "repos": [
              "projectA-docker"
            ],
            "role": []
          },
          "sensitive_attributes": [],
          "private": "blah==",
          "dependencies": [
            "module.project.artifactory_group.contributors"
          ]
        }
      ]
    },
```

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform

**Expected behavior**
The provider should recognize the response from the API and consider something already removed a success.

OR

The provider should recognize that the repo no longer exists and not attempt to remove it.

**Additional context**

Artifactory version: 7.39.10
Terraform v1.2.6
on linux_amd64
+ provider registry.terraform.io/jfrog/artifactory v6.15.1
+ provider registry.terraform.io/jfrog/project v1.1.7

Project definition in `node` module:
```hcl
resource "project" "this" {
  key          = substr(var.display_name, 0, 10)
  display_name = var.display_name
  description  = var.description
  admin_privileges {
    manage_members   = true
    manage_resources = true
    index_resources  = true
  }
  max_storage_in_gibibytes   = var.storage_quota
  block_deployments_on_limit = false
  email_notification         = true

  dynamic "group" {
    for_each = var.groups_contributor
    content {
      name  = group.key
      roles = ["Contributor"]
    }
  }

  group {
    name  = artifactory_group.contributors.name
    roles = ["Contributor"]
  }

  # Repos are created in the repository module. Ignore changes in the project modudle.
  lifecycle {
    ignore_changes = [
      repos
    ]
  }
}
```

Repository definition in `platform` module:
```hcl
resource "artifactory_federated_docker_repository" "this" {
  key                  = "${local.project_key}-docker"
  max_unique_tags      = 300
  project_environments = var.project_environments
  project_key          = local.project_key
  tag_retention        = 100
  xray_index           = true

  dynamic "member" {
    for_each = toset(var.platform_nodes)
    content {
      url     = "https://${member.value}/artifactory/${local.project_key}-docker"
      enabled = true
    }
  }
}
```

### PR DESCRIPTION
**Pull request by alexhung**
Fixes #56 

* Skip error when unassigning repo from project

### CODE REVIEW

**Review by shrajfr12 — DISMISSED** [review]

**Review by danielmkn — APPROVED** [review]

**Review by EvertonSA — COMMENTED** [review]
seems legit

**Review by shrajfr12 — APPROVED** [review]

File: pkg/project/resource_project_repo.go [hunk 1]
```diff
@@ -153,13 +154,36 @@ var deleteRepos = func(ctx context.Context, projectKey string, repoKeys []RepoKe
...
+
+	var errorResp ErrorResponse
+
+	resp, err := m.(*resty.Client).
 		R().
 		AddRetryCondition(retryOnSpecificMsgBody("A timeout occurred")).
 		AddRetryCondition(retryOnSpecificMsgBody("Web server is down")).
 		AddRetryCondition(retryOnSpecificMsgBody("Web server is returning an unknown error")).
 		SetPathParam("repoKey", string(repoKey)).
+		SetError(&errorResp).
```
Comment (mritunjaykumar) [inline pkg/project/resource_project_repo.go:174]: Don't we need to instantiate `errorResp` before passing it to `SetError`?

Comment (alexhung) [reply pkg/project/resource_project_repo.go:174]: Nope. `var` will initialize it (and all its fields, recursively) with default values.

**Review by MahithaB — APPROVED** [review]

File: pkg/project/resource_project_repo.go [hunk 2]
```diff
@@ -153,13 +154,36 @@ var deleteRepos = func(ctx context.Context, projectKey string, repoKeys []RepoKe
...
 		Delete(projectsUrl + "/_/attach/repositories/{repoKey}")
 
+	// Ignore 404 NOT_FOUND error when unassigning repo from project
+	// Possible that repo was deleted out-of-band from TF
+	if resp.StatusCode() == http.StatusNotFound && len(errorResp.Errors) > 0 {
+		for _, error := range errorResp.Errors {
```
Comment (Turhsus) [inline pkg/project/resource_project_repo.go:180]: Does there exist a case where you can get a 404 with an error that isn't NOT_FOUND. I'm curious as to what can be in this Errors array, and if its okay to ignore everything that isn't the not found error if the error exists.

**Review by Turhsus — COMMENTED** [review]
LGTM

File: pkg/project/resource_project_repo.go (hunk 2 above)
Comment (alexhung) [reply pkg/project/resource_project_repo.go:180]: In theory, there shouldn't any other errors for 404. But since this response is not documented and we don't have access to the source code, we don't have ways to know.
