### PR TITLE
Use int64 explicitly with max_storage_in_gibibytes

### LINKED ISSUE #79: provider failed with terraform 1.5.3
**Describe the bug**
Managing a project via terraform 1.4.6 works fine.
same code with terraform 1.5.3 produce the following error:

C:\terraform_1.5.3\Modules>..\terraform apply
module.Artifactory.artifactory_user.build-user: Refreshing state... [id=mydemo-build-system]
module.Artifactory.artifactory_user.admin-user: Refreshing state... [id=e175409]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.Artifactory.project.terraform-project will be created
  + resource "project" "terraform-project" {
      + block_deployments_on_limit = true
      + description                = "mydemo project admin: Terraform Project"
      + display_name               = "mydemo Project"
      + email_notification         = true
      + id                         = (known after apply)
      + key                        = "mydemo"
      + max_storage_in_gibibytes   = 10

      + admin_privileges {
          + index_resources  = true
          + manage_members   = true
          + manage_resources = true
        }

      + member {
          + name  = "e175409"
          + roles = [
              + "Project Admin",
            ]
        }
      + member {
          + name  = "mydemo-build-system"
          + roles = [
              + "Contributor",
            ]
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.Artifactory.project.terraform-project: Creating...
╷
│ Error:
│ 400 POST https://artifactory-dev.amat.com/access/api/v1/projects
│ {
│   "errors" : [ {
│     "code" : "BAD_REQUEST",
│     "message" : "Project Quota cannot be lower than `1073741824` bytes. Input: -2147483648"
│   } ]
│ }
│
│   with module.Artifactory.project.terraform-project,
│   on ..\Artifactory_Project\main.tf line 51, in resource "project" "terraform-project":
│   51: resource "project" "terraform-project" {

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`  7.59.9
- [ ] Your version of terraform 1.5.3

**Expected behavior**
should work as terraform 1.4.6.
changes to max_storage_in_gibibytes produce the same error again

**Additional context**

### PR DESCRIPTION
**Pull request by alexhung**
Close #79 

So 32 bit platform would still work

Add validation for min and max

Remove unused func

### CODE REVIEW

File: pkg/project/resource_project_test.go [hunk 1]
```diff
@@ -124,6 +124,79 @@ func testProjectConfig(name, key string) string {
 	`, params)
 }
 
+func TestAccProjectInvalidMaxStorage(t *testing.T) {
+	invalidMaxStorages := []struct {
```
Comment (danielmkn) [inline pkg/project/resource_project_test.go:128]: I like this idea :)

**Review by danielmkn — APPROVED** [review]
